### ISSUE TITLE
ArgumentError: Column object 'index' already assigned to Table 'investor_9_test'

### ISSUE THREAD

**Issue by nmb10** [franc3000/bartok#24]
http://bartok.herokuapp.com/models/investor/92/positives

Exception on /models/investor/92/positives/json [GET]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/app/bartok/models/views.py", line 162, in investor_positives_json
    query = InvestorPositive(investor=pk).query
  File "/app/bartok/models/models.py", line 162, in __new__
    cls._cache[investor] = type('InvestorPositive', (Model,), meta)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 609, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 55, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 394, in _setup_table
    **table_kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 416, in __new__
    metadata._remove_table(name, schema)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 411, in __new__
    table._init(name, metadata, *args, **kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 488, in _init
    self._init_items(*args)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 72, in _init_items
    item._set_parent_with_dispatch(self)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/base.py", line 433, in _set_parent_with_dispatch
    self._set_parent(parent)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1256, in _set_parent
    existing.description
ArgumentError: Column object 'index' already assigned to Table 'investor_9_test'

**Comment by nmb10** [comment]
Done.
