### ISSUE TITLE
Overview page should show 404 http error if region not found. Now it shows 500 error.

### ISSUE THREAD

**Issue by nmb10** [franc3000/bartok#38]
http://bartok.herokuapp.com/regions/overview/no-such-region

Exception on /regions/overview/CO-Jake [GET]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/app/bartok/regions/views.py", line 165, in overview
    stat = db.session.get_bind().execute(text(query), dataset=region.dataset)
AttributeError: 'NoneType' object has no attribute 'dataset'

**Comment by nmb10** [comment]
Done.
